#! /bin/sh

# (The MIT License)
#
# Copyright (c) 2013-2018 Kura
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the 'Software'), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

### BEGIN INIT INFO
# Provides:          Blackhole
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the Blackhole MTA
# Description:       Starts Blackhole using start-stop-daemon
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CONF=/etc/blackhole.conf
NAME=Blackhole
DESC="Blackhole MTA"
DAEMON_OPTS=""
DAEMON=/usr/local/bin/blackhole
pidfile=/var/run/blackhole.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 1

if test -f $CONF
then
  # shellcheck source=/dev/null
  . $CONF
else
  echo "Failed to open conf: $CONF"
  exit 1
fi

SDAEMON_OPTS="$DAEMON_OPTS -c $CONF -b"

. /lib/lsb/init-functions

start() {
  start-stop-daemon --start --quiet --pidfile "$pidfile" --exec "$DAEMON" -- "$SDAEMON_OPTS"
}

stop() {
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile "$pidfile" --exec "$DAEMON"
}

configtest() {
  $DAEMON -c $CONF -t
}

case "$1" in
  start)
    log_daemon_msg "Starting" "$DESC"
    start
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_progress_msg "already started"
         log_end_msg 0 ;;
      *) log_end_msg 1 ;;
    esac
    ;;
  stop)
    log_daemon_msg "Stopping" "$DESC"
    stop
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_progress_msg "already stopped"
         log_end_msg 0 ;;
      *) log_end_msg 1 ;;
    esac
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p "$pidfile" "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  configtest)
    configtest
    ;;
  *)
    log_action_msg "Usage: $SCRIPTNAME {start|stop|restart|status|configtest}"
    exit 1
    ;;
esac
