#! /bin/sh

### BEGIN INIT INFO
# Provides:          blackhole
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the blackhole MTA
# Description:       starts blackhole using start-stop-daemon
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CONF=/etc/blackhole.conf
NAME=blackhole
DESC="blackhole mta"
DAEMON_OPTS=""
DAEMON=/usr/local/bin/blackhole
pidfile=/var/run/blackhole.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

if test -f $CONF
then
  . $CONF
else
  echo "Failed to open conf: ${CONF}"
  exit
fi

SDAEMON_OPTS="${DAEMON_OPTS} -c ${CONF} -b"

. /lib/lsb/init-functions

start() {
  start-stop-daemon --start --quiet --pidfile $pidfile --exec $DAEMON -- $SDAEMON_OPTS
}

stop() {
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pidfile --exec $DAEMON
}

configtest() {
  $DAEMON -c ${CONF} -t
}

case "$1" in
  start)
    log_daemon_msg "Starting" $DESC
    start
    case "$?" in
            0) log_end_msg 0 ;;
            1) log_progress_msg "already started"
               log_end_msg 0 ;;
            *) log_end_msg 1 ;;
    esac
    ;;
  stop)
    log_daemon_msg "Stopping" $DESC
    stop
    case "$?" in
            0) log_end_msg 0 ;;
            1) log_progress_msg "already stopped"
               log_end_msg 0 ;;
            *) log_end_msg 1 ;;
    esac
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $pidfile $DAEMON $NAME && exit 0 || exit $?
    ;;
  configtest)
    configtest
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/${NAME} {start|stop|restart|status|configtest}"
    exit 1
    ;;
esac
