#! /bin/sh

### BEGIN INIT INFO
# Provides:          blackhole
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the blackhole MTA
# Description:       starts blackhole using start-stop-daemon
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CONF="/etc/blackhole.conf"
NAME=blackhole
DESC=blackhole
DAEMON_OPTS=""
DAEMON="/usr/local/bin/blackhole"

test -x $DAEMON || exit 0

if test -f $CONF
then
  . $CONF
else
  echo "Failed to open conf: ${CONF}"
  exit
fi

SDAEMON_OPTS="${DAEMON_OPTS} --conf=${CONF}"

set -e

. /lib/lsb/init-functions

start() {
  cmd="start-stop-daemon -S --quiet --pidfile $pid --exec $DAEMON -- $SDAEMON_OPTS start"
  if $cmd
  then
    log_end_msg 0
  else
    log_end_msg 1
  fi

}

stop() {
  if [ -e $pid ]
  then
    cmd="start-stop-daemon -K --quiet --pidfile $pid"
  else
    log_end_msg 1
  fi
  if $cmd
  then
    rm -f $pid
    log_end_msg 0
  else
    log_end_msg 1
  fi
}

status() {
  if [ -e $pid ]
  then
    status_of_proc -p $pid $DAEMON blackhole && exit 0 || exit $?
  fi
  echo
}


case "$1" in
  start)
    log_daemon_msg "Starting" $DESC
    start
    ;;
  stop)
    log_daemon_msg "Stopping" $DESC
    stop
    ;;
  restart)
    log_daemon_msg "Stopping" $DESC
    stop
    log_daemon_msg "Starting" $DESC
    start
    ;;
  status)
    log_daemon_msg "Status of" $DESC
    status
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/${NAME} {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
